In [2]:
1 != (2 or 1)

True

In [3]:
import numpy as np

CB = np.array([[1, 0, -3/2], [1, -2, -5/2], [0, 0, 1]])
print(CB)
CA  = np.array([[0, -2, 2], [-2, 0, 6], [0, 0, 1]])
Pc = np.array([2, 0.5, 1])

np.matmul(CB, Pc)


[[ 1.   0.  -1.5]
 [ 1.  -2.  -2.5]
 [ 0.   0.   1. ]]


array([ 0.5, -1.5,  1. ])

In [4]:
E1 = np.matmul(CA, np.linalg.inv(CB))
E1

array([[-1.,  1.,  3.],
       [-2.,  0.,  3.],
       [ 0.,  0.,  1.]])

In [5]:
Rot = np.array([[0, 1, 0], [-1, 0, 0], [0, 0, 1]])
Scale1 = np.array([[1, 0, 0], [0, -1, 0], [0, 0, 1]])
Trans = np.array([[1, 0, -3], [0, 1, 1], [0, 0, 1]])
Scale2 = np.array([[-1, 0, 0], [0, 1, 0], [0, 0, 1]])

transform = np.matmul(np.matmul(Rot, Scale1), np.matmul(Trans, Scale2))
np.matmul(transform, np.array([1, 3, 1]))

array([-4,  4,  1])

In [6]:
mat = np.array([[1, 1, 0, 1], [-1, 1, 0, 2], [0, 0, 1, 0], [0, 0, 0, 1]])
# matin = np.linalg.inv(mat)
obj = np.array([0, 1, 1, 1])
np.matmul(mat, obj)


array([2, 3, 1, 1])

In [7]:
matin

NameError: name 'matin' is not defined

In [ ]:
C5 = np.array([[1, 2, 1], [-1, 0, 3], [2, 1, 4]])
C5i = np.linalg.inv(C5)

np.matmul(C5, C5i)

In [ ]:
np.cross(np.array([0, 0, 1]), np.array([1, 0, 0]))

In [ ]:
np.cross(np.array([0, 0, 1]), np.array([0, -1, 0]))

In [ ]:
np.linalg.inv(np.array([[0, 1, 0, 0], [-1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]))

In [ ]:
def constraintCheck(p):
    '''
    The function to check constraints
    '''
    count = 0
    met_constraints = []
    

    if  (p[6] < p[0]):
        # print("A > G", p[6], p[0])
        count += 1
        met_constraints.append(1)
    if  abs(p[6] - p[2]) == 1:
        # print("|G – C| = 1", p[6], p[2])
        count += 1
        met_constraints.append(2)
    if  p[2] != p[3]:
        # print("D != C", p[3], p[2])
        count += 1
        met_constraints.append(3)
    if  p[6] != p[5]:
        # print("G != F", p[6], p[5])
        count += 1
        met_constraints.append(4)
    if  abs(p[4] - p[5])%2 != 0:
        # print("|E – F| is odd", p[4], p[5])
        count += 1
        met_constraints.append(5)
    if  (p[0] <= p[7]):
        # print("A ≤ H", p[0], p[7])
        count += 1
        met_constraints.append(6)
    if  abs(p[7] - p[2]) %2 == 0:
        # print("|H – C| is even", p[7], p[2])
        count += 1
        met_constraints.append(7)
    if  p[4] != p[2]:
        # print("E != C", p[4], p[2])
        count += 1
        met_constraints.append(8)
    if  p[5] != p[7]:
        # print("H != F", p[7], p[5])
        count += 1
        met_constraints.append(9)
    if  abs(p[5] - p[1]) == 1:
        # print("|F – B| = 1", p[5], p[1])
        count += 1
        met_constraints.append(10)
    if  p[7] != p[3]:
        # print("H != D", p[7], p[3])
        count += 1
        met_constraints.append(11)
    if  p[4] < p[3] - 1:
        # print("E < D – 1", p[4], p[3])
        count += 1
        met_constraints.append(12)
    if p[2] != p[5]:
        # print("C != F", p[2], p[5])
        count += 1
        met_constraints.append(13)
    if  p[6] < p[7]:
        # print("G < H", p[6], p[7])
        count += 1
        met_constraints.append(14)
    if  p[3] >= p[6]:
        # print("D ≥ G", p[3], p[6])
        count += 1
        met_constraints.append(15)
    if  p[4] != p[7] - 2:
        # print("E != H – 2", p[4], p[7])
        count += 1
        met_constraints.append(16)
    if  p[3] != p[5] - 1:
        # print("D != F – 1", p[3], p[5])
        count += 1
        met_constraints.append(17)
    
    return count, met_constraints



In [ ]:
def calc_prob(scores):
    denom = sum(scores)
    sum_so_far = 0
    scores_norm = []
    probs = []
    

    for i in scores:
        
        prob_param = (sum_so_far, sum_so_far+i/denom)
        sum_so_far+=i/denom
        scores_norm.append(prob_param)
        probs.append(round(i/denom, 3))
    return [(round(a[0], 3), round(a[1], 3)) for a in scores_norm], probs

def find(prob, norm_score):

    for i, p in list(enumerate(norm_score)):
        if prob > p[0] and prob < p[1]:
            return i
        



In [ ]:

def pairings(world, norm_scores):
    char_map = {
        0:"A", 
        1:"B",
        2:"C",
        3:"D",
        4:"E",
        5:"F",
        6:"G",
        7:"H"
    }
    newresults = []
    for i in range(4):
        one = np.random.rand(1)
        two = np.random.rand(1)
        at = np.random.randint(1, 8)

        m1 = np.random.randint(1, 8)
        m2 = np.random.randint(1, 4)
        m3 = np.random.randint(1, 8)
        m4 = np.random.randint(1, 4)
        
        print(f"{char_map[find(one, norm_scores)]}, {world[find(one, norm_scores)]}, {char_map[find(two, norm_scores)]}, {world[find(two, norm_scores)]}, at: {at}")
        print(f"mutate {char_map[find(one, norm_scores)]} at {m1 + 1} to {m2}")
        print(f"mutate {char_map[find(two, norm_scores)]} at {m3 + 1} to {m4}")
    
        a1 = world[find(one, norm_scores)][0:at]
        a2 = world[find(one, norm_scores)][at:]
        b1 = world[find(two, norm_scores)][0:at]
        b2 = world[find(two, norm_scores)][at:]
        a = a1 + b2
        a[m1] = m2
        b = b1 + a2
        b[m3] = m4
        newresults.append(a)
        newresults.append(b)

        # print(f"first: {a}, second:{b}")
    return newresults




    

In [ ]:
worlds0 = [[1,1,1,1,1,1,1,1],
[2,2,2,2,2,2,2,2],
[3,3,3,3,3,3,3,3],
[4,4,4,4,4,4,4,4],
[1,2,3,4,1,2,3,4],
[4,3,2,1,4,3,2,1],
[1,2,1,2,1,2,1,2],
[3,4,3,4,3,4,3,4]
]
scores0 = []
for i in worlds0:
    count, met = constraintCheck(i)
    print(f"constraints met: {met}, {count}")
    scores0.append(count)

norm, reg = calc_prob(scores0)
print(norm)

find(0.3, norm)



In [ ]:
worlds1 = [[3, 3, 3, 3, 3, 3, 1, 4], 
[3, 4, 3, 1, 3, 4, 3, 3],
[1, 3, 3, 4, 3, 4, 3, 4],
[3, 4, 3, 2, 1, 2, 3, 4],
[4, 3, 2, 1, 4, 2, 1, 2],
[1, 2, 1, 2, 1, 3, 2, 1],
[4, 4, 1, 4, 1, 2, 3, 4],
[1, 2, 4, 4, 4, 4, 4, 4],
]
scores1 = []
for i in worlds1:
    count, met = constraintCheck(i)
    print(f"{count}")
    scores1.append(count)

calc_prob(scores1)

In [ ]:
world2 = [[3, 4, 3, 2, 3, 4, 3, 4],
[4, 4, 1, 4, 1, 2, 3, 3],
[1, 2, 3, 4, 4, 4, 4, 4],
[4, 4, 1, 4, 1, 2, 2, 4],
[4, 2, 3, 4, 3, 4, 3, 4],
[1, 3, 7, 3, 4, 2, 1, 2],
[1, 2, 1, 2, 1, 2, 7, 4],
[4, 4, 1, 1, 1, 3, 2, 1]
]
scores2 = []
for i in world2:
    count, met = constraintCheck(i)
    print(f"{count}")
    scores2.append(count)

norm2, reg2 = calc_prob(scores2)
results = pairings(world2, norm2)
print(results)

In [ ]:
world3=[[4, 2, 3, 4, 3, 4, 4, 4], 
[1, 1, 3, 4, 4, 4, 3, 4], 
[4, 4, 1, 4, 1, 1, 2, 4], 
[4, 4, 1, 4, 1, 2, 2, 2], 
[1, 3, 7, 3, 4, 2, 1, 1], 
[1, 2, 3, 4, 2, 4, 4, 4], 
[4, 2, 3, 4, 1, 2, 3, 3], 
[4, 4, 1, 4, 3, 4, 1, 4]
]
scores3 = []
for i in world3:
    count, met = constraintCheck(i)
    print(f"{count}")
    scores3.append(count)

norm3, reg3 = calc_prob(scores3)
# results = pairings(world3, norm3)
print(norm3, reg3)

In [ ]:
world4=[[1, 3, 7, 3, 1, 2, 1, 1], 
[1, 2, 3, 4, 2, 4, 2, 4], 
[4, 4, 1, 4, 3, 4, 1, 3], 
[4, 4, 1, 4, 2, 4, 1, 4], 
[4, 4, 1, 1, 3, 4, 1, 4], 
[4, 4, 1, 4, 1, 1, 2, 4], 
[4, 4, 1, 4, 1, 2, 2, 2], 
[4, 2, 3, 4, 3, 4, 4, 1]

]
scores4 = []
for i in world4:
    count, met = constraintCheck(i)
    print(f"{count}")
    scores4.append(count)

norm4, reg4 = calc_prob(scores4)
print(norm4, reg4)
results = pairings(world4, norm4)
print(results)


In [ ]:
world5=[[4, 4, 3, 4, 1, 2, 3, 3], 
[4, 2, 1, 4, 1, 2, 2, 1], 
[4, 3, 3, 3, 4, 2, 1, 1], 
[1, 3, 7, 4, 2, 2, 3, 3],
 [4, 2, 3, 3, 4, 2, 1, 1], 
[1, 3, 7, 4, 3, 4, 3, 4], 
[1, 2, 7, 4, 2, 4, 4, 4], 
[1, 2, 3, 3, 1, 2, 1, 1]

]
scores5 = []
for i in world5:
    count, met = constraintCheck(i)
    print(f"{count}")
    scores5.append(count)

norm5, reg5 = calc_prob(scores5)
print(norm5, reg5)
# results = pairings(world5, norm5)
# print(results)

NameError: name 'constraintCheck' is not defined

In [ ]:
def constraintCheck(p):
    '''
    The function to check constraints
    '''
    count = 0
    met_constraints = []
    

    if  (p[6] < p[0]):
        # print("A > G", p[6], p[0])
        count += 1
        met_constraints.append(1)
    if  abs(p[6] - p[2]) == 1:
        # print("|G – C| = 1", p[6], p[2])
        count += 1
        met_constraints.append(2)
    if  p[2] != p[3]:
        # print("D != C", p[3], p[2])
        count += 1
        met_constraints.append(3)
    if  p[6] != p[5]:
        # print("G != F", p[6], p[5])
        count += 1
        met_constraints.append(4)
    if  abs(p[4] - p[5])%2 != 0:
        # print("|E – F| is odd", p[4], p[5])
        count += 1
        met_constraints.append(5)
    if  (p[0] <= p[7]):
        # print("A ≤ H", p[0], p[7])
        count += 1
        met_constraints.append(6)
    if  abs(p[7] - p[2]) %2 == 0:
        # print("|H – C| is even", p[7], p[2])
        count += 1
        met_constraints.append(7)
    if  p[4] != p[2]:
        # print("E != C", p[4], p[2])
        count += 1
        met_constraints.append(8)
    if  p[5] != p[7]:
        # print("H != F", p[7], p[5])
        count += 1
        met_constraints.append(9)
    if  abs(p[5] - p[1]) == 1:
        # print("|F – B| = 1", p[5], p[1])
        count += 1
        met_constraints.append(10)
    if  p[7] != p[3]:
        # print("H != D", p[7], p[3])
        count += 1
        met_constraints.append(11)
    if  p[4] < p[3] - 1:
        # print("E < D – 1", p[4], p[3])
        count += 1
        met_constraints.append(12)
    if p[2] != p[5]:
        # print("C != F", p[2], p[5])
        count += 1
        met_constraints.append(13)
    if  p[6] < p[7]:
        # print("G < H", p[6], p[7])
        count += 1
        met_constraints.append(14)
    if  p[3] >= p[6]:
        # print("D ≥ G", p[3], p[6])
        count += 1
        met_constraints.append(15)
    if  p[4] != p[7] - 2:
        # print("E != H – 2", p[4], p[7])
        count += 1
        met_constraints.append(16)
    if  p[3] != p[5] - 1:
        # print("D != F – 1", p[3], p[5])
        count += 1
        met_constraints.append(17)
    
    return count, met_constraints



In [ ]:
def calc_prob(scores):
    denom = sum(scores)
    sum_so_far = 0
    scores_norm = []
    probs = []
    

    for i in scores:
        
        prob_param = (sum_so_far, sum_so_far+i/denom)
        sum_so_far+=i/denom
        scores_norm.append(prob_param)
        probs.append(round(i/denom, 3))
    return [(round(a[0], 3), round(a[1], 3)) for a in scores_norm], probs

def find(prob, norm_score):

    for i, p in list(enumerate(norm_score)):
        if prob > p[0] and prob < p[1]:
            return i
        
def pairings(world, norm_scores):
    char_map = {
        0:"A", 
        1:"B",
        2:"C",
        3:"D",
        4:"E",
        5:"F",
        6:"G",
        7:"H"
    }
    newresults = []
    for i in range(4):
        one = np.random.rand(1)
        two = np.random.rand(1)
        at = np.random.randint(1, 8)

        m1 = np.random.randint(1, 8)
        m2 = np.random.randint(1, 4)
        m3 = np.random.randint(1, 8)
        m4 = np.random.randint(1, 4)
        
        print(f"{char_map[find(one, norm_scores)]}, {world[find(one, norm_scores)]}, {char_map[find(two, norm_scores)]}, {world[find(two, norm_scores)]}, at: {at}")
        print(f"mutate {char_map[find(one, norm_scores)]} at {m1 + 1} to {m2}")
        print(f"mutate {char_map[find(two, norm_scores)]} at {m3 + 1} to {m4}")
    
        a1 = world[find(one, norm_scores)][0:at]
        a2 = world[find(one, norm_scores)][at:]
        b1 = world[find(two, norm_scores)][0:at]
        b2 = world[find(two, norm_scores)][at:]
        a = a1 + b2
        a[m1] = m2
        b = b1 + a2
        b[m3] = m4
        newresults.append(a)
        newresults.append(b)

        # print(f"first: {a}, second:{b}")
    return newresults


In [ ]:
current_pop = [[1,1,1,1,1,1,1,1],
[2,2,2,2,2,2,2,2],
[3,3,3,3,3,3,3,3],
[4,4,4,4,4,4,4,4],
[1,2,3,4,1,2,3,4],
[4,3,2,1,4,3,2,1],
[1,2,1,2,1,2,1,2],
[3,4,3,4,3,4,3,4]
]

def genetic_algo(population, iter):
    world = population
    scores = []

    while iter != 0:
        for i in world:
            count, met = constraintCheck(i)
            print(count)
            if count == 14:
                return i
            scores.append(count)

        norm, reg = calc_prob(scores)
        print(norm, reg)
        world = pairings(world, norm)
        print(world)
        scores = []
    
        


        iter-=1
    
    print("not found")


genetic_algo(current_pop, 5)

5
5
5
5
12
9
9
9
[(0, 0.085), (0.085, 0.169), (0.169, 0.254), (0.254, 0.339), (0.339, 0.542), (0.542, 0.695), (0.695, 0.847), (0.847, 1.0)] [0.085, 0.085, 0.085, 0.085, 0.203, 0.153, 0.153, 0.153]
H, [3, 4, 3, 4, 3, 4, 3, 4], E, [1, 2, 3, 4, 1, 2, 3, 4], at: 5
mutate H at 4 to 3
mutate E at 3 to 3
A, [1, 1, 1, 1, 1, 1, 1, 1], C, [3, 3, 3, 3, 3, 3, 3, 3], at: 5
mutate A at 8 to 2
mutate C at 7 to 1
B, [2, 2, 2, 2, 2, 2, 2, 2], G, [1, 2, 1, 2, 1, 2, 1, 2], at: 6
mutate B at 6 to 3
mutate G at 4 to 3
F, [4, 3, 2, 1, 4, 3, 2, 1], H, [3, 4, 3, 4, 3, 4, 3, 4], at: 5
mutate F at 2 to 2
mutate H at 4 to 3
[[3, 4, 3, 3, 3, 2, 3, 4], [1, 2, 3, 4, 1, 4, 3, 4], [1, 1, 1, 1, 1, 3, 3, 2], [3, 3, 3, 3, 3, 1, 1, 1], [2, 2, 2, 2, 2, 3, 1, 2], [1, 2, 1, 3, 1, 2, 2, 2], [4, 2, 2, 1, 4, 4, 3, 4], [3, 4, 3, 3, 3, 3, 2, 1]]
10
11
6
7
12
10
12
10
[(0, 0.128), (0.128, 0.269), (0.269, 0.346), (0.346, 0.436), (0.436, 0.59), (0.59, 0.718), (0.718, 0.872), (0.872, 1.0)] [0.128, 0.141, 0.077, 0.09, 0.154, 0.128, 0